from pathlib import Path

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


# ============================================================
# SETUP
# ============================================================

driver = webdriver.Chrome()
driver.maximize_window()

wait = WebDriverWait(driver, 10)

# Screenshots will be saved automatically
SCREENSHOT_DIR = Path("screenshots")
SCREENSHOT_DIR.mkdir(exist_ok=True)


def take_screenshot(name):
    path = SCREENSHOT_DIR / f"{name}.png"
    driver.save_screenshot(str(path))
    print(f"Screenshot saved: {path}")


try:

    # ========================================================
    # 1. WORKING WITH KEYBOARD EVENTS
    # ========================================================

    print("\n--- 1. Keyboard Events ---")

    driver.get("https://the-internet.herokuapp.com/key_presses")

    key_box = wait.until(
        EC.presence_of_element_located((By.ID, "target"))
    )

    key_box.click()

    # Send ENTER key
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # Read the actual result generated by the page
    result = wait.until(
        EC.visibility_of_element_located((By.ID, "result"))
    )

    result_text = result.text.strip()

    print("Keyboard result:", result_text)

    # Verify that the result element received a value
    assert result_text != ""

    print("ENTER key verification: PASS")

    take_screenshot("01_keyboard_events")


    # ========================================================
    # 2. WORKING WITH SCROLLBAR
    # ========================================================

    print("\n--- 2. Scrollbar ---")

    driver.get("https://the-internet.herokuapp.com/large")

    # Scroll to bottom
    driver.execute_script(
        "window.scrollTo(0, document.body.scrollHeight);"
    )

    bottom_position = driver.execute_script(
        "return window.scrollY;"
    )

    assert bottom_position > 0

    print("Scrolled to bottom")
    print("Bottom scroll verification: PASS")

    take_screenshot("02_scroll_bottom")

    # Scroll back to top
    driver.execute_script("window.scrollTo(0, 0);")

    top_position = driver.execute_script(
        "return window.scrollY;"
    )

    assert top_position == 0

    print("Scrolled back to top")
    print("Top scroll verification: PASS")


    # ========================================================
    # 3. WORKING WITH DRAG AND DROP
    # ========================================================

    print("\n--- 3. Drag and Drop ---")

    driver.get("https://the-internet.herokuapp.com/drag_and_drop")

    source = wait.until(
        EC.presence_of_element_located((By.ID, "column-a"))
    )

    target = wait.until(
        EC.presence_of_element_located((By.ID, "column-b"))
    )

    ActionChains(driver).drag_and_drop(
        source, target
    ).perform()

    print("Drag and drop action executed")

    # Verify DOM elements still exist after the action
    assert source.is_displayed()
    assert target.is_displayed()

    print("Drag and drop verification: PASS")

    take_screenshot("03_drag_and_drop")


    # ========================================================
    # 4. HANDLING IFRAMES
    # ========================================================

    print("\n--- 4. IFrames ---")

    driver.get("https://the-internet.herokuapp.com/iframe")

    iframe = wait.until(
        EC.presence_of_element_located((By.ID, "mce_0_ifr"))
    )

    driver.switch_to.frame(iframe)

    editor = wait.until(
        EC.presence_of_element_located((By.TAG_NAME, "body"))
    )

    # Select existing text and replace it
    editor.click()

    ActionChains(driver) \
        .key_down(Keys.CONTROL) \
        .send_keys("a") \
        .key_up(Keys.CONTROL) \
        .send_keys("Hello from Selenium IFrame!") \
        .perform()

    iframe_text = driver.execute_script(
        "return arguments[0].innerText;",
        editor
    )

    print("IFrame text:", iframe_text)

    assert "Hello from Selenium IFrame!" in iframe_text

    print("IFrame verification: PASS")

    take_screenshot("04_iframe")

    driver.switch_to.default_content()

    print("Returned to main page")


    # ========================================================
    # 5. DISABLED / ENABLED ELEMENT STATE
    # ========================================================

    print("\n--- 5. Disabled / Enabled Element State ---")

    driver.get("https://the-internet.herokuapp.com/dynamic_controls")

    input_box = wait.until(
        EC.presence_of_element_located(
            (By.CSS_SELECTOR, "#input-example input")
        )
    )

    # Input should initially be disabled
    initial_state = input_box.is_enabled()

    print("Initial input enabled:", initial_state)

    assert initial_state is False

    print("Disabled state verification: PASS")

    # Click Enable
    enable_button = driver.find_element(
        By.XPATH,
        "//div[@id='input-example']//button"
    )

    enable_button.click()

    # Wait until input becomes enabled
    wait.until(lambda d: input_box.is_enabled())

    enabled_state = input_box.is_enabled()

    print("After Enable button:", enabled_state)

    assert enabled_state is True

    print("Enabled state verification: PASS")

    # Enter text
    input_box.send_keys("Selenium Automation")

    input_value = input_box.get_attribute("value")

    assert input_value == "Selenium Automation"

    print("Text entered successfully")
    print("Input value verification: PASS")

    take_screenshot("05_enabled_element")


    # ========================================================
    # 6. GET TEXT ON ELEMENT
    # ========================================================

    print("\n--- 6. Get Text On Element ---")

    driver.get("https://the-internet.herokuapp.com/login")

    heading = wait.until(
        EC.presence_of_element_located((By.TAG_NAME, "h2"))
    )

    element_text = heading.text

    print("Element text:", element_text)

    assert element_text == "Login Page"

    print("Element text verification: PASS")


    # ========================================================
    # 7. GET VALUE OF ELEMENT ATTRIBUTE
    # ========================================================

    print("\n--- 7. Get Attribute Value ---")

    username = driver.find_element(
        By.ID,
        "username"
    )

    type_value = username.get_attribute("type")
    name_value = username.get_attribute("name")

    print("Type attribute:", type_value)
    print("Name attribute:", name_value)

    assert type_value == "text"
    assert name_value == "username"

    print("Attribute verification: PASS")

    # Check value attribute
    username.send_keys("testuser")

    input_value = username.get_attribute("value")

    print("Value attribute:", input_value)

    assert input_value == "testuser"

    print("Value attribute verification: PASS")


    # ========================================================
    # FINAL RESULT
    # ========================================================

    print("\n========================================")
    print("ALL AUTOMATION TESTS PASSED SUCCESSFULLY")
    print("========================================")


finally:
    driver.quit()